//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBook.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int SeqNo { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid CategoryItemId { get; set; }
        public System.DateTime TradeDate { get; set; }
        public int Money { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
    
        public virtual CategoryItem CategoryItem { get; set; }
    }
}
